"use client";

/**
 * ConnectionsTab — incoming + outgoing artifact edges rendered as ArtifactCards,
 * grouped by edge type and direction.
 *
 * P3-02: Connections tab — data from useArtifactEdges, cards via ArtifactCard,
 *         grouped by edge type + direction, per-group counts, empty state.
 * P3-03: Add / remove connection flow.
 *         - "Add connection" button → ArtifactSearchDialog (single-select)
 *         - Edge type selection via Select before confirming
 *         - POST /api/artifacts/:id/link via linkArtifact()
 *         - Remove via unlinkEdge(source, target, { edgeType }) → optimistic refetch
 *         - Toasts on success / error
 *
 * The ContextRail connections list is NOT touched — this tab is additive.
 */

import React, { useState, useCallback, useMemo } from "react";
import { Plus, Trash2, ArrowDownLeft, ArrowUpRight, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { useArtifactEdges } from "@/hooks/useArtifactEdges";
import type { ArtifactEdgeItem, EdgeType } from "@/hooks/useArtifactEdges";
import {
  linkArtifact,
  unlinkEdge,
  type ArtifactEdgeType,
} from "@/lib/api/artifacts";
import { ArtifactCard } from "@/components/library/artifact-card";
import { ArtifactSearchDialog } from "@/components/search/ArtifactSearchDialog";
import type { ArtifactCard as ArtifactCardType } from "@/types/artifact";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

// ---------------------------------------------------------------------------
// Edge type label / colour maps (mirrors ArtifactDetailClient constants)
// ---------------------------------------------------------------------------

const EDGE_TYPE_LABELS: Record<string, string> = {
  derived_from: "Derived from",
  supports: "Supports",
  relates_to: "Relates to",
  references: "References",
  supersedes: "Supersedes",
  contradicts: "Contradicts",
  contains: "Contains",
  generated_by: "Generated by",
  possible_duplicate_of: "Possible duplicate of",
  redirects_to: "Redirects to",
  merged_into: "Merged into",
  handoff_to: "Hands off to",
  handoff_from: "Handed off from",
};

const EDGE_TYPE_COLOURS: Record<string, string> = {
  derived_from: "bg-sky-100 text-sky-800 dark:bg-sky-900/40 dark:text-sky-300",
  supports: "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/40 dark:text-emerald-300",
  relates_to: "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300",
  references: "bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-300",
  supersedes: "bg-violet-100 text-violet-800 dark:bg-violet-900/40 dark:text-violet-300",
  contradicts: "bg-rose-100 text-rose-800 dark:bg-rose-900/40 dark:text-rose-300",
  contains: "bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-300",
  generated_by: "bg-teal-100 text-teal-800 dark:bg-teal-900/40 dark:text-teal-300",
  possible_duplicate_of: "bg-orange-100 text-orange-800 dark:bg-orange-900/40 dark:text-orange-300",
  redirects_to: "bg-indigo-100 text-indigo-800 dark:bg-indigo-900/40 dark:text-indigo-300",
  merged_into: "bg-purple-100 text-purple-800 dark:bg-purple-900/40 dark:text-purple-300",
  handoff_to: "bg-amber-100 text-amber-900 dark:bg-amber-900/40 dark:text-amber-200",
  handoff_from: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/40 dark:text-yellow-300",
};

/** All selectable edge types for the "Add connection" flow. */
const LINK_EDGE_TYPES: ArtifactEdgeType[] = [
  "relates_to",
  "derived_from",
  "supports",
  "references",
  "supersedes",
  "contradicts",
  "contains",
  "generated_by",
  "possible_duplicate_of",
  "redirects_to",
  "merged_into",
  "handoff_to",
];

// ---------------------------------------------------------------------------
// Internal types
// ---------------------------------------------------------------------------

interface EdgeGroup {
  direction: "outgoing" | "incoming";
  edgeType: EdgeType;
  items: ArtifactEdgeItem[];
}

// ---------------------------------------------------------------------------
// EdgeTypeBadge
// ---------------------------------------------------------------------------

function EdgeTypeBadge({ edgeType }: { edgeType: EdgeType }) {
  const label = EDGE_TYPE_LABELS[edgeType] ?? edgeType;
  const colour =
    EDGE_TYPE_COLOURS[edgeType] ?? "bg-muted text-muted-foreground";
  return (
    <span
      aria-label={`Edge type: ${label}`}
      className={cn(
        "inline-flex items-center rounded-sm px-1.5 py-0.5 text-[11px] font-medium leading-tight",
        colour,
      )}
    >
      {label}
    </span>
  );
}

// ---------------------------------------------------------------------------
// Stub card for peer artifacts not yet in the overlay
// ---------------------------------------------------------------------------

function PeerStubCard({
  item,
  onRemove,
  removing,
}: {
  item: ArtifactEdgeItem;
  onRemove: (peerId: string, edgeType: EdgeType) => void;
  removing: boolean;
}) {
  return (
    <div
      className={cn(
        "flex items-center justify-between gap-3 rounded-md border bg-card/50 px-3 py-2",
        removing && "opacity-60",
      )}
    >
      <div className="min-w-0 flex-1">
        <p className="truncate text-sm font-medium text-foreground/80">
          {item.title ?? item.artifact_id}
        </p>
        {item.subtype && (
          <p className="text-xs text-muted-foreground">{item.subtype}</p>
        )}
      </div>
      <button
        type="button"
        aria-label={`Remove connection to ${item.title ?? item.artifact_id}`}
        disabled={removing}
        onClick={() => onRemove(item.artifact_id, item.type)}
        className={cn(
          "flex shrink-0 items-center justify-center rounded-sm p-1",
          "text-muted-foreground hover:text-destructive",
          "focus:outline-none focus-visible:ring-2 focus-visible:ring-ring",
          "disabled:cursor-not-allowed disabled:opacity-40 transition-colors",
        )}
      >
        {removing ? (
          <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden="true" />
        ) : (
          <Trash2 className="h-3.5 w-3.5" aria-hidden="true" />
        )}
      </button>
    </div>
  );
}

// ---------------------------------------------------------------------------
// ConnectionCard — wraps ArtifactCard with a remove action overlay
// ---------------------------------------------------------------------------

function ConnectionCard({
  item,
  direction,
  onRemove,
  removing,
  onPeek,
}: {
  item: ArtifactEdgeItem;
  direction: "incoming" | "outgoing";
  onRemove: (peerId: string, edgeType: EdgeType) => void;
  removing: boolean;
  onPeek?: (id: string) => void;
}) {
  // Build a minimal ArtifactCardType from the edge item so we can reuse ArtifactCard.
  const cardArtifact = useMemo<ArtifactCardType>(
    () => ({
      id: item.artifact_id,
      workspace: "library" as const,
      type: item.subtype ?? "concept",
      subtype: item.subtype ?? null,
      title: item.title ?? item.artifact_id,
      status: "active" as const,
      file_path: `${item.subtype ?? "artifact"}/${item.artifact_id}`,
      created: null,
      updated: null,
    }),
    [item],
  );

  return (
    <div
      className={cn(
        "relative",
        removing && "opacity-60 pointer-events-none",
      )}
    >
      <ArtifactCard
        artifact={cardArtifact}
        variant="list"
        displayVariant="compact"
        onPeek={onPeek}
        onCardClick={onPeek ? (e, a) => { e.preventDefault(); onPeek(a.id); } : undefined}
      />

      {/* Remove button overlay */}
      <button
        type="button"
        aria-label={`Remove ${direction === "incoming" ? "incoming" : "outgoing"} connection to ${item.title ?? item.artifact_id}`}
        disabled={removing}
        onClick={() => onRemove(
          direction === "outgoing" ? item.artifact_id : item.artifact_id,
          item.type,
        )}
        className={cn(
          "absolute right-2 top-2 z-10",
          "flex items-center justify-center rounded-sm p-1",
          "bg-background/80 text-muted-foreground",
          "hover:bg-destructive/10 hover:text-destructive",
          "focus:outline-none focus-visible:ring-2 focus-visible:ring-ring",
          "disabled:cursor-not-allowed disabled:opacity-40 transition-colors",
        )}
      >
        {removing ? (
          <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden="true" />
        ) : (
          <Trash2 className="h-3.5 w-3.5" aria-hidden="true" />
        )}
      </button>
    </div>
  );
}

// ---------------------------------------------------------------------------
// EdgeGroupSection
// ---------------------------------------------------------------------------

function EdgeGroupSection({
  group,
  onRemove,
  removingKey,
  onPeek,
}: {
  group: EdgeGroup;
  onRemove: (peerId: string, edgeType: EdgeType, direction: "incoming" | "outgoing") => void;
  removingKey: string | null;
  onPeek?: (id: string) => void;
}) {
  const dirIcon =
    group.direction === "outgoing" ? (
      <ArrowUpRight className="h-3.5 w-3.5 text-muted-foreground" aria-hidden="true" />
    ) : (
      <ArrowDownLeft className="h-3.5 w-3.5 text-muted-foreground" aria-hidden="true" />
    );

  const dirLabel = group.direction === "outgoing" ? "outgoing" : "incoming";

  return (
    <section
      aria-label={`${EDGE_TYPE_LABELS[group.edgeType] ?? group.edgeType} (${dirLabel}, ${group.items.length})`}
    >
      {/* Group header */}
      <div className="mb-2 flex items-center gap-2">
        {dirIcon}
        <EdgeTypeBadge edgeType={group.edgeType} />
        <span className="text-xs text-muted-foreground">
          {group.direction === "outgoing" ? "This artifact → peer" : "Peer → this artifact"}
        </span>
        <span
          className="ml-auto text-xs font-semibold text-muted-foreground"
          aria-label={`${group.items.length} connection${group.items.length === 1 ? "" : "s"}`}
        >
          {group.items.length}
        </span>
      </div>

      {/* Cards */}
      <div className="flex flex-col gap-2 pl-5">
        {group.items.map((item) => {
          const key = `${group.direction}:${group.edgeType}:${item.artifact_id}`;
          const removing = removingKey === key;

          if (!item.title) {
            // Peer not in overlay — use stub card
            return (
              <PeerStubCard
                key={key}
                item={item}
                onRemove={(peerId, edgeType) =>
                  onRemove(peerId, edgeType, group.direction)
                }
                removing={removing}
              />
            );
          }

          return (
            <ConnectionCard
              key={key}
              item={item}
              direction={group.direction}
              onRemove={(peerId, edgeType) =>
                onRemove(peerId, edgeType, group.direction)
              }
              removing={removing}
              onPeek={onPeek}
            />
          );
        })}
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// AddConnectionDialog — step 2: pick edge type after artifact is chosen
// ---------------------------------------------------------------------------

interface AddConnectionDialogProps {
  open: boolean;
  targetArtifact: ArtifactCardType | null;
  edgeType: ArtifactEdgeType;
  onEdgeTypeChange: (v: ArtifactEdgeType) => void;
  onConfirm: () => void;
  onCancel: () => void;
  isSubmitting: boolean;
}

function AddConnectionDialog({
  open,
  targetArtifact,
  edgeType,
  onEdgeTypeChange,
  onConfirm,
  onCancel,
  isSubmitting,
}: AddConnectionDialogProps) {
  return (
    <Dialog open={open} onOpenChange={(v) => { if (!v) onCancel(); }}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle>Add connection</DialogTitle>
        </DialogHeader>

        <div className="space-y-4 py-2">
          {targetArtifact && (
            <div className="rounded-md border bg-muted/40 px-3 py-2">
              <p className="text-xs font-medium text-muted-foreground">Target artifact</p>
              <p className="mt-0.5 truncate text-sm font-semibold text-foreground">
                {targetArtifact.title}
              </p>
              {targetArtifact.type && (
                <p className="text-xs text-muted-foreground">{targetArtifact.type}</p>
              )}
            </div>
          )}

          <div className="space-y-1.5">
            <label
              htmlFor="edge-type-select"
              className="text-xs font-semibold uppercase tracking-wider text-muted-foreground/70"
            >
              Connection type
            </label>
            <Select
              value={edgeType}
              onValueChange={(v) => onEdgeTypeChange(v as ArtifactEdgeType)}
              disabled={isSubmitting}
            >
              <SelectTrigger id="edge-type-select" className="w-full">
                <SelectValue placeholder="Select relationship…" />
              </SelectTrigger>
              <SelectContent>
                {LINK_EDGE_TYPES.map((t) => (
                  <SelectItem key={t} value={t}>
                    {EDGE_TYPE_LABELS[t] ?? t}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        <div className="flex justify-end gap-2 pt-2">
          <Button variant="outline" onClick={onCancel} disabled={isSubmitting}>
            Cancel
          </Button>
          <Button onClick={onConfirm} disabled={isSubmitting}>
            {isSubmitting ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" aria-hidden="true" />
                Linking…
              </>
            ) : (
              "Add connection"
            )}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface ConnectionsTabProps {
  /** The ID of the artifact whose connections we are viewing/editing. */
  artifactId: string;
  /**
   * Optional callback to open the peek modal for a connected artifact.
   * When provided, clicking a ConnectionCard opens the peek modal instead of
   * navigating to the full artifact detail page.
   * Wire to useArtifactPeek().openPeek (P3-05).
   */
  onPeek?: (id: string) => void;
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export function ConnectionsTab({ artifactId, onPeek }: ConnectionsTabProps) {
  const { data, isLoading, isError, refetch } = useArtifactEdges(artifactId);

  // ---- "Add connection" flow state ----------------------------------------
  const [searchOpen, setSearchOpen] = useState(false);
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [pendingTarget, setPendingTarget] = useState<ArtifactCardType | null>(null);
  const [pendingEdgeType, setPendingEdgeType] = useState<ArtifactEdgeType>("relates_to");
  const [isSubmitting, setIsSubmitting] = useState(false);

  // ---- Remove state --------------------------------------------------------
  // Key format: "<direction>:<edgeType>:<peerId>"
  const [removingKey, setRemovingKey] = useState<string | null>(null);

  // ---- Toast --------------------------------------------------------------
  const [toast, setToast] = useState<{ kind: "success" | "error"; text: string } | null>(null);
  const toastTimer = React.useRef<ReturnType<typeof setTimeout> | null>(null);

  const showToast = useCallback((kind: "success" | "error", text: string) => {
    if (toastTimer.current) clearTimeout(toastTimer.current);
    setToast({ kind, text });
    toastTimer.current = setTimeout(() => setToast(null), 3000);
  }, []);

  React.useEffect(() => {
    return () => { if (toastTimer.current) clearTimeout(toastTimer.current); };
  }, []);

  // ---- Build grouped sections ---------------------------------------------
  const groups = useMemo<EdgeGroup[]>(() => {
    if (!data) return [];

    const result: EdgeGroup[] = [];

    // Group outgoing by edge type
    const outBuckets = new Map<EdgeType, ArtifactEdgeItem[]>();
    for (const item of data.outgoing) {
      const existing = outBuckets.get(item.type);
      if (existing) { existing.push(item); }
      else { outBuckets.set(item.type, [item]); }
    }
    for (const [edgeType, items] of outBuckets) {
      result.push({ direction: "outgoing", edgeType, items });
    }

    // Group incoming by edge type
    const inBuckets = new Map<EdgeType, ArtifactEdgeItem[]>();
    for (const item of data.incoming) {
      const existing = inBuckets.get(item.type);
      if (existing) { existing.push(item); }
      else { inBuckets.set(item.type, [item]); }
    }
    for (const [edgeType, items] of inBuckets) {
      result.push({ direction: "incoming", edgeType, items });
    }

    return result;
  }, [data]);

  const totalCount = (data?.outgoing.length ?? 0) + (data?.incoming.length ?? 0);

  // ---- Add connection handlers --------------------------------------------

  const handleSearchSelect = useCallback((selected: ArtifactCardType[]) => {
    const target = selected[0];
    if (!target) return;
    setSearchOpen(false);
    setPendingTarget(target);
    setPendingEdgeType("relates_to");
    setConfirmOpen(true);
  }, []);

  const handleConfirmLink = useCallback(async () => {
    if (!pendingTarget) return;
    setIsSubmitting(true);
    try {
      await linkArtifact(artifactId, {
        target_id: pendingTarget.id,
        edge_type: pendingEdgeType,
      });
      setConfirmOpen(false);
      setPendingTarget(null);
      showToast("success", "Connection added");
      refetch();
    } catch (err) {
      showToast("error", err instanceof Error ? err.message : "Failed to add connection");
    } finally {
      setIsSubmitting(false);
    }
  }, [artifactId, pendingTarget, pendingEdgeType, showToast, refetch]);

  const handleCancelConfirm = useCallback(() => {
    setConfirmOpen(false);
    setPendingTarget(null);
  }, []);

  // ---- Remove handler -----------------------------------------------------

  const handleRemove = useCallback(
    async (peerId: string, edgeType: EdgeType, direction: "incoming" | "outgoing") => {
      const key = `${direction}:${edgeType}:${peerId}`;
      setRemovingKey(key);

      // For outgoing edges: source = artifactId, target = peerId.
      // For incoming edges: source = peerId, target = artifactId.
      const sourceId = direction === "outgoing" ? artifactId : peerId;
      const targetId = direction === "outgoing" ? peerId : artifactId;

      try {
        await unlinkEdge(sourceId, targetId, { edgeType });
        showToast("success", "Connection removed");
        refetch();
      } catch (err) {
        showToast("error", err instanceof Error ? err.message : "Failed to remove connection");
      } finally {
        setRemovingKey(null);
      }
    },
    [artifactId, showToast, refetch],
  );

  // ---- Render -------------------------------------------------------------

  return (
    <div className="flex flex-col gap-6 py-2">
      {/* Toast */}
      {toast && (
        <div
          role="status"
          aria-live="polite"
          className={cn(
            "flex items-center gap-2 rounded-md border px-3 py-2 text-xs font-medium",
            toast.kind === "success"
              ? "border-emerald-500/30 bg-emerald-50 text-emerald-700 dark:border-emerald-500/20 dark:bg-emerald-950/30 dark:text-emerald-400"
              : "border-destructive/30 bg-destructive/5 text-destructive",
          )}
        >
          <span aria-hidden="true" className={cn(
            "size-1.5 rounded-full",
            toast.kind === "success" ? "bg-emerald-500" : "bg-destructive",
          )} />
          {toast.text}
        </div>
      )}

      {/* Header row */}
      <div className="flex items-center justify-between gap-4">
        <div>
          <h3 className="text-sm font-semibold text-foreground">
            Connections
            {!isLoading && (
              <span className="ml-1.5 text-xs font-normal text-muted-foreground">
                ({totalCount})
              </span>
            )}
          </h3>
          <p className="mt-0.5 text-xs text-muted-foreground">
            Incoming and outgoing edges grouped by relationship type
          </p>
        </div>

        <Button
          size="sm"
          variant="outline"
          onClick={() => setSearchOpen(true)}
          className="shrink-0 gap-1.5"
          aria-label="Add a new connection to this artifact"
        >
          <Plus className="h-3.5 w-3.5" aria-hidden="true" />
          Add connection
        </Button>
      </div>

      {/* Body */}
      {isLoading ? (
        <div className="flex flex-col gap-3" aria-busy="true" aria-label="Loading connections">
          {[...Array(3)].map((_, i) => (
            <div
              key={i}
              className="h-16 animate-pulse rounded-md border bg-muted/30"
            />
          ))}
        </div>
      ) : isError ? (
        <div
          role="alert"
          className="rounded-md border border-destructive/30 bg-destructive/5 px-3 py-4 text-center text-sm text-destructive"
        >
          Failed to load connections. Try refreshing the page.
        </div>
      ) : totalCount === 0 ? (
        /* Empty state */
        <div
          role="status"
          className="flex flex-col items-center justify-center gap-2 rounded-md border border-dashed py-12 text-center"
        >
          <p className="text-sm text-muted-foreground">No connections yet</p>
          <p className="text-xs text-muted-foreground/60">
            Use &ldquo;Add connection&rdquo; to link related artifacts.
          </p>
        </div>
      ) : (
        <div className="flex flex-col gap-6">
          {groups.map((group) => (
            <EdgeGroupSection
              key={`${group.direction}:${group.edgeType}`}
              group={group}
              onRemove={handleRemove}
              removingKey={removingKey}
              onPeek={onPeek}
            />
          ))}
        </div>
      )}

      {/* Step 1: artifact search */}
      <ArtifactSearchDialog
        open={searchOpen}
        onOpenChange={setSearchOpen}
        onSelect={(artifacts) => handleSearchSelect(artifacts)}
        mode="single"
        title="Find artifact to connect"
      />

      {/* Step 2: confirm + pick edge type */}
      <AddConnectionDialog
        open={confirmOpen}
        targetArtifact={pendingTarget}
        edgeType={pendingEdgeType}
        onEdgeTypeChange={setPendingEdgeType}
        onConfirm={() => void handleConfirmLink()}
        onCancel={handleCancelConfirm}
        isSubmitting={isSubmitting}
      />
    </div>
  );
}
