"use client";

/**
 * HandoffChain — renders artifact_edges as a visual breadcrumb-style chain.
 *
 * Shows the lineage of an artifact: source → knowledge → synthesis,
 * visualised as a horizontal chain of node pills connected by directional
 * arrows. Uses edge types `generated_by | handoff_from | handoff_to |
 * derived_from` to infer direction and label each link.
 *
 * Design: monospaced IDs, muted tones, compact — sits in the sidebar or
 * below the artifact header without competing with the reader content.
 *
 * Renders nothing when `edges` is null, undefined, or empty.
 *
 * P3-06: initial implementation using `artifact_edges` from ArtifactDetail.
 * Future: link to /artifact/[id] for each node once backend returns titles.
 *
 * Stitch reference: design spec §3.1 addendum §6 "Handoff Chain".
 * WCAG 2.1 AA: edge direction communicated via both icon and text label
 * (never icon-only). Color never the sole carrier of information.
 */

import { cn } from "@/lib/utils";
import type { ArtifactEdge, ArtifactEdgeType } from "@/types/artifact";

// ---------------------------------------------------------------------------
// Edge type labels and visual weight
// ---------------------------------------------------------------------------

const EDGE_LABELS: Record<ArtifactEdgeType, string> = {
  generated_by: "generated by",
  handoff_from: "handoff from",
  handoff_to: "handoff to",
  derived_from: "derived from",
  supports: "supports",
  relates_to: "relates to",
  supersedes: "supersedes",
  contradicts: "contradicts",
  contains: "contains",
};

/** Edge types that represent a direct knowledge lineage (bolder rendering). */
const LINEAGE_EDGE_TYPES: Set<ArtifactEdgeType> = new Set([
  "generated_by",
  "handoff_from",
  "handoff_to",
  "derived_from",
]);

// ---------------------------------------------------------------------------
// Truncate long IDs for display
// ---------------------------------------------------------------------------

function shortId(id: string): string {
  if (id.length <= 14) return id;
  return `${id.slice(0, 6)}…${id.slice(-4)}`;
}

// ---------------------------------------------------------------------------
// Single edge node
// ---------------------------------------------------------------------------

interface EdgeNodeProps {
  id: string;
  role: "source" | "target";
  isCurrentArtifact?: boolean;
}

function EdgeNode({ id, role, isCurrentArtifact }: EdgeNodeProps) {
  return (
    <span
      aria-label={`${isCurrentArtifact ? "This artifact" : role}: ${id}`}
      className={cn(
        "inline-flex items-center rounded border px-1.5 py-0.5",
        "font-mono text-[10px] leading-tight",
        isCurrentArtifact
          ? "border-primary/40 bg-primary/5 text-primary"
          : "border-border bg-muted/50 text-muted-foreground",
      )}
    >
      {isCurrentArtifact ? "this" : shortId(id)}
    </span>
  );
}

// ---------------------------------------------------------------------------
// Arrow between nodes
// ---------------------------------------------------------------------------

function EdgeArrow({ label, isLineage }: { label: string; isLineage: boolean }) {
  return (
    <span
      aria-label={label}
      className={cn(
        "inline-flex items-center gap-0.5 text-[10px]",
        isLineage ? "text-foreground/60" : "text-muted-foreground/50",
      )}
    >
      {/* Left dash */}
      <span aria-hidden="true" className="h-px w-3 bg-current" />
      {/* Arrow label */}
      <span className="hidden sm:inline text-[9px] leading-none whitespace-nowrap">
        {label}
      </span>
      {/* Arrowhead */}
      <svg
        aria-hidden="true"
        className="size-2.5 shrink-0"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="m9 18 6-6-6-6"
        />
      </svg>
    </span>
  );
}

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

export interface HandoffChainProps {
  /** The current artifact's ID — highlighted differently in the chain. */
  currentArtifactId: string;
  /** Edges from `ArtifactDetail.artifact_edges` — null/undefined renders nothing. */
  edges?: ArtifactEdge[] | null;
  className?: string;
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export function HandoffChain({
  currentArtifactId,
  edges,
  className,
}: HandoffChainProps) {
  if (!edges || edges.length === 0) return null;

  // Sort: lineage edges first (generated_by, handoff_*, derived_from), then others
  const sorted = [...edges].sort((a, b) => {
    const aIsLineage = LINEAGE_EDGE_TYPES.has(a.edge_type) ? 0 : 1;
    const bIsLineage = LINEAGE_EDGE_TYPES.has(b.edge_type) ? 0 : 1;
    return aIsLineage - bIsLineage;
  });

  return (
    <div
      aria-label="Artifact handoff chain"
      className={cn("flex flex-col gap-1.5", className)}
    >
      {sorted.map((edge, i) => {
        const label = EDGE_LABELS[edge.edge_type] ?? edge.edge_type;
        const isLineage = LINEAGE_EDGE_TYPES.has(edge.edge_type);

        return (
          <div
            // biome-ignore lint/suspicious/noArrayIndexKey: edges may share artifact IDs with different types
            key={`${edge.from_artifact_id}-${edge.edge_type}-${edge.to_artifact_id}-${i}`}
            className="flex flex-wrap items-center gap-1 overflow-hidden"
          >
            <EdgeNode
              id={edge.from_artifact_id}
              role="source"
              isCurrentArtifact={edge.from_artifact_id === currentArtifactId}
            />
            <EdgeArrow label={label} isLineage={isLineage} />
            <EdgeNode
              id={edge.to_artifact_id}
              role="target"
              isCurrentArtifact={edge.to_artifact_id === currentArtifactId}
            />
          </div>
        );
      })}
    </div>
  );
}
